// ** Constants for Action types
export const ARCHIVE = 'ARCHIVE'
export const GET_ALL_DATA = 'GET_ALL_DATA'
export const GET_DATA = 'GET_DATA'
export const GET_EXAM_SCHEDULE = 'GET_EXAM_SCHEDULE'
export const ADD_EXAM_SCHEDULE = 'ADD_EXAM_SCHEDULE'
export const UPDATE_EXAM_SCHEDULE = 'UPDATE_EXAM_SCHEDULE'
export const DELETE_EXAM_SCHEDULE = 'DELETE_EXAM_SCHEDULE'
export const RESTORE_EXAM_SCHEDULE = 'RESTORE_EXAM_SCHEDULE'
