export const GET_ALL_DATA = 'GET_ALL_DATA'
export const GET_DATA = 'GET_DATA'
export const GET_TEACHER = 'GET_TEACHER'
export const ADD_TEACHER = 'ADD_TEACHER'
export const UPDATE_TEACHER = 'UPDATE_TEACHER'
export const DELETE_TEACHER = 'DELETE_TEACHER'
export const RESTORE_TEACHER = 'RESTORE_TEACHER'
export const ARCHIVE_TEACHER = 'ARCHIVE_TEACHER'

