// ** Constants for Action types
export const ARCHIVE = 'ARCHIVE'
export const GET_ALL_DATA = 'GET_ALL_DATA'
export const GET_DATA = 'GET_DATA'
export const GET_REGISTRATIONS = 'GET_REGISTRATIONS'
export const ADD_REGISTRATIONS = 'ADD_REGISTRATIONS'
export const UPDATE_REGISTRATIONS = 'UPDATE_REGISTRATIONS'
export const DELETE_REGISTRATIONS = 'DELETE_REGISTRATIONS'
export const RESTORE_REGISTRATIONS = 'RESTORE_REGISTRATIONS'